// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xohnxjicjealjucofpbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvaG54amljamVhbGp1Y29mcGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzY0OTcsImV4cCI6MjA2MDM1MjQ5N30.n53ZztRD9K5X-tvCns5zLEaCZIpYkr_DDdSrE4SxoyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);